name: Release notes generator
author: Decathlon <developers@decathlon.com>
description: This Github action <strong>automatically creates a release notes</strong> when a milestone is closed.
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: tag
  color: blue
